name: Report a bug - create Jira issue

on:
  workflow_dispatch:
    inputs:
      port_context:
        required: true
      short_title:
        required: true
        type: string
      description:
        required: true
        type: string

jobs:
  create_jira_issue:
    runs-on: ubuntu-latest
    steps: 
    - name: Login
      uses: atlassian/gajira-login@v3
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

    - name: Log start of Jira issue creation
      uses: port-labs/port-github-action@v1
      with:
        clientId: ${{ secrets.PORT_CLIENT_ID }}
        clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
        operation: PATCH_RUN
        runId: ${{ fromJson( inputs.port_context).runId }}
        logMessage: |
            Creating a new Jira issue.. ⛴️

    - name: Create Jira issue
      id: create
      uses: atlassian/gajira-create@v3
      with:
        project: POR
        issuetype: Bug
        summary:  Bug | ${{ inputs.short_title }}
        description: |
          ${{ inputs.description }}

          Reported by: ${{ fromJson(inputs.port_context).user_first_name }} ${{ fromJson(inputs.port_context).user_last_name }}
    
    - name: Log issue creation
      uses: port-labs/port-github-action@v1
      with:
        clientId: ${{ secrets.PORT_CLIENT_ID }}
        clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
        operation: PATCH_RUN
        link: https://hadorco.atlassian.net/browse/${{ steps.create.outputs.issue }}
        runId: ${{ fromJson(inputs.port_context).runId }}
        logMessage: |
           Jira issue created! ✅
           
           The issue id is: ${{ steps.create.outputs.issue }}
